search: "yes"
nrounds: 10
eta: c(0.01, 0.1)
max_depth: c(4, 7, 10)
subsample: c(0.5, 0.75)
colsample_bytree: c(0.33, 0.67)
min_child_weight: c(1, 10)
max_delta_step: c(1, 10)
ncluster: 10
train: "~/projects/physionet/physionet_data/small_dataset/train.csv"
valid: "~/projects/physionet/physionet_data/small_dataset/test.csv"
outcome: "SepsisLabel"
search_results: "here('david', 'xgboost', 'xgboost_search.csv')"
model: "here('david', 'xgboost', 'xgboost.model')"
