---
title: ""
author: "David Dai"
date: "Last updated: `r format(Sys.Date(), '%b %d, %Y')`"
output:
    html_document:
        theme: paper
        toc: true
        toc_float: true
        highlight: kate
        # runtime: shiny
---


```{r knitr_init, echo=FALSE, cache=FALSE, include = F}
library(knitr)
library(rmdformats)

## Global options
opts_chunk$set(echo=FALSE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               cache.lazy = F)
opts_knit$set(width=80)

```

```{r, cache = F}
library(tidyverse)
# library(CHART)
library(here)
library(conflicted)
library(lubridate)
library(survival)
library(survminer)

# Conflicts
conflict_prefer("here", "here")
conflict_prefer("filter", "dplyr")

```

```{r}
test <- read_csv("Z:/LKS-CHART/Projects/physionet_sepsis_project/data/splits/split_0/test_split_0.csv")

df <- test %>% 
    group_by(subject) %>% 
    arrange(ICULOS) %>% 
    fill(HR:Temp) %>% 
    fill(HR:Temp, .direction = "up") %>% 
    ungroup() %>% 
    select(HR:Temp, Age, Gender, ICULOS, SepsisLabel, subject)



```

```{r}
# Create survival object
surv_obj <- Surv(time = df$futime,
           event = ovarian$fustat)

# KM curves
km_fit <- survfit(surv_obj ~ rx, data = ovarian)
ggsurvplot(km_fit, data = ovarian)

# Cox PH model
cox_fit <- coxph(surv_obj ~ rx + resid.ds + age + ecog.ps,
                 data = ovarian)

```

